### ISSUE TITLE
Issues with Install

### ISSUE THREAD

**Issue by decapstrike** [pewresearch/pewanalytics#3]
Having problems getting this installed via either method, v1.0.0's setup.py errors, and the downloaded version of 1.0.1 has those errors corrected but the same version number, a folder is made but no tools are installed. 

running install
running build
running build_py
running install_lib
running install_egg_info
Writing /usr/local/lib/python3.8/dist-packages/pewanalytics-1.0.1.egg-info

**Comment by patrickvankessel** [comment]
Sorry to hear you're having trouble installing - definitely want to get this resolved for you!  Could you provide more details on the exact commands you're running and the full output that's getting printed?  And what OS are you installing on?

**Comment by Ethan-Harris0n** [comment]
Following up on this - I've tried install from pip and via source with setup.py install (even though I believe that method is depreciated). I'm on an m1 mac running miniconda. Any tips for install? I am able to load the general package but any methods (e.g. from pewanalytics import pewanalytics.x) fails.

When I attempt to install via pip i get this error - ERROR: Command errored out with exit status 128: git clone -q 'ssh://****@github.com/seanpianka/zipcodes.git' /private/var/folders/4f/03z15p_d3hq6c8x_swps3clc0000gn/T/pip-install-rml6m07s/zipcodes_d57b85f83b4d42699291b42d6d5acac5 Check the logs for full command output.

**Comment by bribroder** [comment]
Hi there! Thank you for reporting this issue. We've released a comprehensive update of this package and these dependency issues should be resolved now. Please do open a new issue for us if you still have trouble installing this package.
