### ISSUE TITLE
ModuleNotFoundError: No module named 'pewanalytics.text'

### ISSUE THREAD

**Issue by keyuchen21** [pewresearch/pewanalytics#4]
ModuleNotFoundError: No module named 'pewanalytics.text'

It is ok to "import pewanalytics"
but not ok to "from pewanalytics.text.topics import TopicModel"

I followed the instruction here:
https://pewresearch.github.io/pewanalytics/text.html#date-extraction

<img width="637" alt="WeChata6509492451909613f775ba90aefbf9a" src="https://user-images.githubusercontent.com/54015474/137597993-8eed47af-7744-423b-9965-e7bfa00d2062.png">

**Comment by bribroder** [comment]
Hi there! Thank you for reporting this issue. We've released a comprehensive update of this package and these dependency issues should be resolved now. Please do open a new issue for us if you still have trouble installing this package.
