### ISSUE TITLE
pip install failed on both colab and local envirment

### ISSUE THREAD

**Issue by keyuchen21** [pewresearch/pewanalytics#5]
<img width="1091" alt="WeChat23b1bf624337d0b9beeeb082c9f573ea" src="https://user-images.githubusercontent.com/54015474/137598301-fdb7ae32-e0a9-43aa-9778-e0f980d82dbe.png">

**Comment by bribroder** [comment]
Hi there! Thank you for reporting this issue. We've released a comprehensive update of this package and these dependency issues should be resolved now. Please do open a new issue for us if you still have trouble installing this package.
