### ISSUE TITLE
failed to install

### ISSUE THREAD

**Issue by keyuchen21** [pewresearch/pewanalytics#6]
I created a new environment through mini conda
then pip install pattern
here is the error

<img width="1270" alt="image" src="https://user-images.githubusercontent.com/54015474/167172164-22234749-5db2-4677-afac-5dd0e9f6916a.png">

**Comment by griverorz** [comment]
Thanks, @km5ar. The problem does not seem related to `pewanalytics` but, perhaps, to `pattern` so I am going to close this issue. 

The error itself can maybe be addressed by [installing the MySQL client or updating your PATH.](https://stackoverflow.com/questions/5178292/pip-install-mysql-python-fails-with-environmenterror-mysql-config-not-found) If the error persists, you may want to report it in [the `pattern` repository.](https://github.com/clips/pattern)
